<a href="https://colab.research.google.com/github/pranitamdivashikar/Python-Assignments/blob/main/Pandas_Assignment_Day_10(Pranita).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [1]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [2]:
# a =

a = pd.Series([100, 200, 300, 400])

Print a, and data type

In [3]:
print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [4]:
a[2]

np.int64(300)

What are the values of index for series a?

In [5]:
a.index

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [6]:
a.index = ['c', 'a', 'b', 'd']

Access the value in the series with index 'd'

In [7]:
a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [8]:
a.sort_index()

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [9]:
# b =

b = pd.Series([800, 450, 100], index=['e', 'f', 'g'])

Append b series at the end of a series

In [10]:
# The 'append' method for pandas Series has been removed.
# You should use pd.concat() instead.
a = pd.concat([a, b])

In [11]:
#print a again after appending b into it

print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [12]:
# a =

a = a.sort_values(ascending=False)
print(a.index)

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [13]:
# df =

df = pd.DataFrame(a)

What is the shape of the datafarme <br>
(also, what does it imply?)

In [14]:
df.shape    # This implies that the dataframe has 7 rows and 1 column

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [33]:
# yep its same as the series.

df.index

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tail represent?)

In [34]:
print(df.head())   # Returns the first 5 rows of the DataFrame by default, allowing you to quickly inspect the structure and beginning of the dataset
print(df.tail())   # Returns the last 5 rows of the DataFrame by default, which is useful for checking the end of the dataset

     0
e  800
f  450
d  400
b  300
a  200
     0
d  400
b  300
a  200
c  100
g  100

Rename the column of the dataframe as 'points'

In [35]:
df.columns = ['points']

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [36]:
#Create fruits array

# fruits =

fruits = pd.Series(np.resize(np.array(['orange', 'mango', 'apple']), 7), index=df.index)

In [37]:
#Create series fruits out of fruits array

# fruits =

fruits = pd.Series(fruits, index=df.index)

Change the index of fruits to the index of dataframe df

In [38]:
fruits.index = df.index

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [39]:
df['fruits'] = fruits
print(df.head())

   points  fruits
e     800  orange
f     450   mango
d     400   apple
b     300  orange
a     200   mango

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [40]:
# d1 =

d1 = pd.DataFrame({
    'city': ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
    'Temperature': [15, 22, 20, 26, -2]
})

Print(d1)

In [41]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [42]:
d1.shape

(5, 2)

Set city = d1['city']

In [46]:
city = d1['city']

print city <br>
What is the type of city.

In [48]:
print(type('city'))

<class 'str'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [49]:
# d2 =

d2 = pd.DataFrame({
    'city': ['Bengalaru', 'Coimbatore', 'Srirangam', 'Pondicherry'],
    'Temperature': [24, 35, 36, 39]
})

print the shape of this dataframe

In [50]:
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [52]:
d3 = pd.concat([d1, d2], ignore_index=True)

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [53]:
d3[d3['Temperature'] <= 20]

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [54]:
d3[d3['Temperature'] >= 35]

          city  Temperature
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [55]:
# write function here

# def is_ut(x):

#     # write code below

# d3['is_ut'] =

def is_ut(x):
    return x in ['Chandigarh', 'Pondicherry', 'Delhi']

d3['is_ut'] = d3['city'].apply(is_ut)

In [56]:
# print d3

print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
5    Bengalaru           24  False
6   Coimbatore           35  False
7    Srirangam           36  False
8  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [57]:
# write function here

def c_to_f(temp):
   return (temp * 9/5) + 32

In [58]:
# check function c_to_f(10)

print(c_to_f(10))

50.0

In [59]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [60]:
d1[d1['city'].isin(['Chandigarh', 'Delhi'])]

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [61]:
d1[(d1['Temperature'] * 9 / 5 + 32) > 90]

Empty DataFrame
Columns: [city, Temperature]
Index: []

Select only the first three rows of the dataframe d1.

In [66]:
d1.head(3)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [67]:
d1.iloc[:, -2:]

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

## Groupby

In [68]:
# Create a dataframe using dictionary of your choice

# data =

data = {
    'Department': ['IT', 'HR', 'IT', 'HR', 'Finance', 'Finance'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Salary': [70000, 50000, 80000, 52000, 90000, 95000],
    'Years_Exp': [3, 2, 5, 3, 7, 8]
}

df_group = pd.DataFrame(data)

In [69]:
# Use Groupby of single column with aggregate sum()

df_group.groupby('Department')['Salary'].sum()

Department
Finance    185000
HR         102000
IT         150000
Name: Salary, dtype: int64

In [70]:
# Use Groupby of single column with aggregate count()

df_group.groupby('Department').count()

            Employee  Salary  Years_Exp
Department
Finance            2       2          2
HR                 2       2          2
IT                 2       2          2

In [71]:
# Use Groupby of single column with aggregate min() and max()

df_group.groupby('Department')['Salary'].agg(['min', 'max'])

              min    max
Department
Finance     90000  95000
HR          50000  52000
IT          70000  80000

In [81]:
# Use Groupby of any 2 columns with aggregate mean()

df_group.groupby('Department')['Years_Exp'].mean()

Department
Finance    7.5
HR         2.5
IT         4.0
Name: Years_Exp, dtype: float64

In [82]:
# Use Groupby of any 2 columns with aggregate min() and max()

df_group.groupby(['Department', 'Years_Exp']).agg(['min', 'max'])

                     Employee          Salary
                          min      max    min    max
Department Years_Exp
Finance    7              Eve      Eve  90000  90000
           8            Frank    Frank  95000  95000
HR         2              Bob      Bob  50000  50000
           3            David    David  52000  52000
IT         3            Alice    Alice  70000  70000
           5          Charlie  Charlie  80000  80000

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [62]:
# a =
a = pd.date_range(start='2020-01-01', end='2021-04-01')

print a

In [63]:
print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [64]:
print(len(a))

457

What is the type of a?

In [65]:
print(type(a))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>